Private events
Rayan84/private-events pull request #1
Opened 2021-02-16 10:53 UTC by patrick-angelos

This project is about using advanced associations and the session hash with rails
We created:
- A simple site that you can sign up (without password)
- The user can create an event if he is logged in
- The user can attend an event if he is logged in

2021-02-16 14:09 UTC, oloomoses requested changes
# Status: Changes Required
Hello team, great job on this project especially the readme :muscle: 
You are almost there. Just a few things to check on :point_down: 
- [ ] Event's index page displays past and upcoming events lists ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from Odin)
- [ ] Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from Odin)
- [ ] Remember to move all your logic into the helpers
##### EventsController

###### `create` action

* [x] uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

###### `index` action

* [x] lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

##### UsersController

###### `show` action

* [x] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

Kindly implement the above changes before submitting another review.
### feel free to reach me on slack [Oloo Moses] incase of doubts or concerns

2021-02-16 14:09 UTC, oloomoses commented on app/views/layouts/application.html.erb
> +    <% end %>
- [ ] Move your logic into helpers

2021-02-16 14:09 UTC, oloomoses commented on app/views/users/new.html.erb
> +<% end %>
- [ ] move this logic into the helpers

2021-02-16 14:09 UTC, oloomoses commented on app/views/events/show.html.erb
> +<% end %>
- [ ] Move this logic into helpers

2021-02-17 08:12 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2021-02-17 08:41 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Rayan84 and @patrick-angelos  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] You have some logic in views: View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
  - [ ] There shoud be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright _=> To make sure that I clarify what you need to change on this reqirement: Ensure that there is no if conditions, and no loops in your view (`.html.erb`) files_
  
#### Resources to help you learn about this:

- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code/)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

# [Optional changes] :yellow_circle:
- [ ] You can add some styin to your page so that it looks way professional 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-17 10:20 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

### Hey @patrick-angelos & @Rayan84 , 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [ ] Add integration test for all the different features, attend an event, unattend an event, login, signup, create event and so on...
- [ ] Test the association between models(this is not hard you can add shoulda gem to make the association test easier).
- [x] Also unit tests to test model validations.

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

2021-02-17 18:08 UTC, MarilenaRoque approved these changes
## Hello Team! :rocket:

Congratulations on achieving all the requirements for this project.
Nice implementation of the tests. :tada:

# Your Project is Approved! 🥇 

### Suggention:
- The feature that separates the past and upcoming events at the show page of the user is working just fine, but the title doesn't indicate the upcoming events. It would be nice to divide it into "Past Events" and "Upcoming Events" instead of Past Events and Attended Events.

Keep going with the hard work! 💪🏻 
Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

2021-02-18 08:05 UTC, merged